### ISSUE TITLE
Add support for 'support tickets'

### ISSUE THREAD

**Issue by johrstrom** [OSC/puppet-module-openondemand#123]
We're looking to enable this feature (below) at OSC sometime soon. Which means, I'd guess, we need puppet support for the same.

We're only enabling `support_ticket.email` support at OSC, so this is about all we'd need.  We don't need all the other fields (like read timeouts), so I'll leave it to you whether you want to implement support for them or not.

```yaml
support_ticket:
  email:
    from: "config@example.com"
    to: "support@support.system.com"
```

https://osc.github.io/ood-documentation/latest/customizations.html#support-tickets
